version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-2:953361230125:task-definition/webapi:9"
        LoadBalancerInfo:
          ContainerName: "webapi"
          ContainerPort: 80
